import { describe, expect, it } from "vitest";
import { chatReducer, initialChatState } from "./reducer";
import { sampleReport } from "../mock";
import type { OptimizationReport } from "@bg3-builds/domain";
const optimizationReport = { kind: "optimization", title: "Bounded result", summary: "Bounded only.", generatedAt: "2026-01-01T00:00:00.000Z", result: { request: { gameVersion: "Patch 8", level: 5, availableAct: 1, combat: { mode: "ranged", targetArmorClass: 15, surprise: false, guaranteedCritical: false, areaTargets: 1 }, maxCandidates: 20 }, build: { ...sampleReport.build, level: 5, classes: [{ classId: "Swords Bard", level: 5 }] }, score: 42, metrics: { custom: {} }, issues: [], bounds: { evaluatedCandidates: 2, maxCandidates: 20, searchScope: "bounded-l5-act1-ranged", globallyOptimal: false }, limitations: ["Bounded only."] } } satisfies OptimizationReport;
describe("chatReducer",()=>{
 it("rekeys the pending response to the server message ID",()=>{ let state=chatReducer(initialChatState,{type:"submit",user:{id:"u",role:"user",text:"build"},assistantId:"client-a"}); state=chatReducer(state,{type:"event",event:{type:"message_start",messageId:"server-a"}}); state=chatReducer(state,{type:"event",event:{type:"text_delta",delta:"Answer"}}); expect(state.messages[1]).toMatchObject({id:"server-a",text:"Answer"}); });
 it("accumulates deltas, tools, and a structured report",()=>{ let state=chatReducer(initialChatState,{type:"submit",user:{id:"u",role:"user",text:"build"},assistantId:"a"}); state=chatReducer(state,{type:"event",event:{type:"text_delta",delta:"First "}}); state=chatReducer(state,{type:"event",event:{type:"text_delta",delta:"answer"}}); state=chatReducer(state,{type:"event",event:{type:"tool_status",tool:{id:"rules",label:"Check rules",status:"running"}}}); state=chatReducer(state,{type:"event",event:{type:"tool_status",tool:{id:"rules",label:"Check rules",status:"complete"}}}); state=chatReducer(state,{type:"event",event:{type:"report",report:optimizationReport}}); expect(state.messages[1]).toMatchObject({text:"First answer",tools:[{status:"complete"}],report:optimizationReport}); });
 it("ends streaming on errors",()=>{ let state=chatReducer(initialChatState,{type:"submit",user:{id:"u",role:"user",text:"build"},assistantId:"a"}); state=chatReducer(state,{type:"event",event:{type:"error",error:{message:"Unavailable"}}}); expect(state.status).toBe("error"); expect(state.messages[1]?.error).toBe("Unavailable"); });
});
